name: build-php80
on:
  push:
    paths:
      - 'php80/**'
    branches:
      - '!*'
      - 'develop'
      - 'stage'
      - 'master'

env:
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
  CI: true

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 30
          persist-credentials: false

      - name: Build
        run: |
          bash php80/build.sh

